language: python
sudo: false

python:
  - "3.5"
#  - "3.6"

#services:
#  - redis-server

# command to install dependencies
install:
  - pip install --upgrade pip wheel
  - pip install --upgrade setuptools
  - pip install tox
  #- pip install tox-travis

# command to run tests
script: tox

#after_success:
#  - pip install codecov
#  - codecov

os:
  - linux

deploy:

  # Deploy to PyPI
  - provider: script
    user: $PYPI_USER
    password: $PYPI_PASSWD
    distributions: "sdist"
    on:
      branch: master

  #- provider: releases
  #  api_key: $GITHUB_AUTH
  #  file: dist/*.tar.gz
  #  file_glob: true
  #  skip_cleanup: true
  #  on:
  #    tags: true